src/Entity/Agent.php
<?php

namespace App\Entity;

use App\Repository\AgentRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: AgentRepository::class)]
class Agent
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nom = null;

    #[ORM\Column(length: 255)]
    private ?string $prenom = null;

    #[ORM\Column(type: Types::DATE_IMMUTABLE)]
    private ?\DateTimeImmutable $date_naissance = null;

    #[ORM\Column(length: 255)]
    private ?string $code_identification = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $nationalite = null;

    #[ORM\ManyToOne(inversedBy: 'agents')]
    private ?Mission $Mission = null;

    #[ORM\OneToMany(mappedBy: 'Agent', targetEntity: Specialite::class)]
    private Collection $specialites;

    public function __construct()
    {
        $this->specialites = new ArrayCollection();
        $this->date_naissance = new \DateTimeImmutable();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getDateNaissance(): ?\DateTimeImmutable
    {
        return $this->date_naissance;
    }

    public function setDateNaissance(\DateTimeImmutable $date_naissance): self
    {
        $this->date_naissance = $date_naissance;

        return $this;
    }

    public function getCodeIdentification(): ?string
    {
        return $this->code_identification;
    }

    public function setCodeIdentification(string $code_identification): self
    {
        $this->code_identification = $code_identification;

        return $this;
    }

    public function getNationalite(): ?string
    {
        return $this->nationalite;
    }

    public function setNationalite(string $nationalite): self
    {
        $this->nationalite = $nationalite;

        return $this;
    }

    public function getMission(): ?Mission
    {
        return $this->Mission;
    }

    public function setMission(?Mission $Mission): self
    {
        $this->Mission = $Mission;

        return $this;
    }

    /**
     * @return Collection<int, Specialite>
     */
    public function getSpecialites(): Collection
    {
        return $this->specialites;
    }

    public function addSpecialite(Specialite $specialite): self
    {
        if (!$this->specialites->contains($specialite)) {
            $this->specialites->add($specialite);
            $specialite->setAgent($this);
        }

        return $this;
    }

    public function removeSpecialite(Specialite $specialite): self
    {
        if ($this->specialites->removeElement($specialite)) {
            // set the owning side to null (unless already changed)
            if ($specialite->getAgent() === $this) {
                $specialite->setAgent(null);
            }
        }

        return $this;
    }
}

src/Form/AgentType.php
<?php

namespace App\Form;

use App\Entity\Agent;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AgentType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom')
            ->add('prenom')
            ->add('date_naissance')
            ->add('code_identification')
            ->add('nationalite')
            ->add('Mission')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Agent::class,
        ]);
    }
}

src/Controller/AgentController.php
<?php

namespace App\Controller;

use App\Entity\Agent;
use App\Form\AgentType;
use App\Repository\AgentRepository;
use Doctrine\Persistence\ManagerRegistry;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

#[Route('/agent')]
class AgentController extends AbstractController
{


    #[Route('/', name: 'agent.list')]
    public function index(ManagerRegistry $doctrine, AgentRepository $repository, PaginatorInterface $paginator, Request $request): Response 
    
    {
        $agents = $paginator->paginate(
        $agents = $repository->findAll(),
            $request->query->getInt('page', 1), /*page number*/
            10 /*limit per page*/
        );

        $repository = $doctrine->getRepository(persistentObject: Agent::class);
        return $this->render('agent/index.html.twig', ['agents' => $agents,]);
    }


    
    #[Route('/{id<\d+>}', name: 'agent.detail')]
    public function detail(Agent $agent = null): Response 
    
    {

        if(!$agent) {
            $this->addFlash(type: 'error', message: "L'agent  n'existe pas");
            return $this->redirectToRoute('agent');
        }
        return $this->render('agent/detail.html.twig', ['agent' => $agent]);
    }

    #[Route('/detail', name: 'app_agent_detail', methods: ['GET'])]
    public function details(AgentRepository $agentRepository, $id ): Response
    {


        return $this->render('agent/detail.html.twig', [
            'agents' => $agentRepository->findby($id),
        ]);
    }
   
   
   
   
   





    //#[Route('/', name: 'app_agent_index', methods: ['GET'])]
   // public function index(AgentRepository $agentRepository): Response
  //  {
      //  return $this->render('agent/index.html.twig', [
         //   'agents' => $agentRepository->findAll(),
       // ]);
  //  }

   // #[Route('/new', name: 'app_agent_new', methods: ['GET', 'POST'])]
   // public function new(Request $request, AgentRepository $agentRepository): Response
   // {
     //   $agent = new Agent();
       // $form = $this->createForm(AgentType::class, $agent);
       // $form->handleRequest($request);

      //  if ($form->isSubmitted() && $form->isValid()) {
         //   $agentRepository->add($agent, true);

         //   return $this->redirectToRoute('app_agent_index', [], Response::HTTP_SEE_OTHER);
       // }

       // return $this->renderForm('agent/new.html.twig', [
         //   'agent' => $agent,
          //  'form' => $form,
       // ]);
   // }

    //#[Route('/{id}', name: 'app_agent_show', methods: ['GET'])]
   // public function show(Agent $agent): Response
    //{
       // return $this->render('agent/show.html.twig', [
      //      'agent' => $agent,
      //  ]);
  //  }

   // #[Route('/{id}/edit', name: 'app_agent_edit', methods: ['GET', 'POST'])]
   // public function edit(Request $request, Agent $agent, AgentRepository $agentRepository): Response
  //  {
    //    $form = $this->createForm(AgentType::class, $agent);
      //  $form->handleRequest($request);

      //  if ($form->isSubmitted() && $form->isValid()) {
         //   $agentRepository->add($agent, true);

          //  return $this->redirectToRoute('app_agent_index', [], Response::HTTP_SEE_OTHER);
      //  }

      // return $this->renderForm('agent/edit.html.twig', [
       //    'agent' => $agent,
        //    'form' => $form,
       // ]);
  //  }

  //  #[Route('/{id}', name: 'app_agent_delete', methods: ['POST'])]
   // public function delete(Request $request, Agent $agent, AgentRepository $agentRepository): Response
   // {
      //  if ($this->isCsrfTokenValid('delete'.$agent->getId(), $request->request->get('_token'))) {
       //     $agentRepository->remove($agent, true);
        //}

       // return $this->redirectToRoute('app_agent_index', [], Response::HTTP_SEE_OTHER);
   // }
}

templates/agent/_delete_form.html.twig
<form method="post" action="{{ path('app_agent_delete', {'id': agent.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ agent.id) }}">
    <button class="btn">Delete</button>
</form>

templates/agent/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/agent/detail.html.twig
{% extends 'base.html.twig' %}

{% block title %}

{{ agent.nom }}
{% endblock %}

{% block body %}
<div class="row mt-3">
    <div class="card" style="width: 18rem;">
        <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTImCcwj7a-CYOiLWDzriL30IU7cLGLLUyMQA&usqp=CAU" class="card-img-top" alt="...">
        <div class="card-body">
<div class="alert alert-sucess">
<h1>{{ agent.nom }}</h1>
<p>{{ agent.prenom }}</p>
</div>
</div>

{% endblock %}

templates/agent/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Agent{% endblock %}

{% block body %}
    <h1>Edit Agent</h1>

    {{ include('agent/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_agent_index') }}">back to list</a>

    {{ include('agent/_delete_form.html.twig') }}
{% endblock %}

templates/agent/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des Agents{% endblock %}

{% block body %}
    <h1>Liste des Agents</h1>

   
<div class="row">
    {% for agent in agents %}
    <div class="card" style="width: 18rem;">
      <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSWYM8ViE4IQ0UIk1_GCi5dVKj2f7r_sJxmeQ&usqp=CAU" class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title">{{ agent.nom }}</h5>
          <h6 class="card-subtitle mb-2 text-muted">{{ agent.prenom }}</h6>
          <a href="{{ path('agent.detail', {id: agent.id})}}" class="btn btn-primary">Voir le détail</a>
        </div>
      </div>
      {% endfor %}
</div>

<div class="navigation d-flex justify-content-center mt-4">
  {{ knp_pagination_render(agents) }}
</div>
{% endblock %}

templates/agent/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Agent{% endblock %}

{% block body %}
    <h1>Create new Agent</h1>

    {{ include('agent/_form.html.twig') }}

    <a href="{{ path('app_agent_index') }}">back to list</a>
{% endblock %}

templates/agent/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Agent{% endblock %}

{% block body %}
    <h1>Agent</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ agent.id }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ agent.nom }}</td>
            </tr>
            <tr>
                <th>Prenom</th>
                <td>{{ agent.prenom }}</td>
            </tr>
            <tr>
                <th>Date_naissance</th>
                <td>{{ agent.dateNaissance ? agent.dateNaissance|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Code_identification</th>
                <td>{{ agent.codeIdentification }}</td>
            </tr>
            <tr>
                <th>Nationalite</th>
                <td>{{ agent.nationalite }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_agent_index') }}">back to list</a>

    <a href="{{ path('app_agent_edit', {'id': agent.id}) }}">edit</a>

    {{ include('agent/_delete_form.html.twig') }}
{% endblock %}