src/Entity/Cible.php
<?php

namespace App\Entity;

use App\Repository\CibleRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CibleRepository::class)]
class Cible
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nom = null;

    #[ORM\Column(length: 255)]
    private ?string $prenom = null;

    #[ORM\Column(type: Types::DATE_IMMUTABLE)]
    private ?\DateTimeImmutable $date_naissance = null;

    #[ORM\Column(length: 255)]
    private ?string $nom_code = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $nationalite = null;

    #[ORM\ManyToOne(inversedBy: 'cibles')]
    private ?Mission $Mission = null;


    public function __construct()
    {
        
        $this->date_naissance = new \DateTimeImmutable();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getDateNaissance(): ?\DateTimeImmutable
    {
        return $this->date_naissance;
    }

    public function setDateNaissance(\DateTimeImmutable $date_naissance): self
    {
        $this->date_naissance = $date_naissance;

        return $this;
    }

    public function getNomCode(): ?string
    {
        return $this->nom_code;
    }

    public function setNomCode(string $nom_code): self
    {
        $this->nom_code = $nom_code;

        return $this;
    }

    public function getNationalite(): ?string
    {
        return $this->nationalite;
    }

    public function setNationalite(string $nationalite): self
    {
        $this->nationalite = $nationalite;

        return $this;
    }

    public function getMission(): ?Mission
    {
        return $this->Mission;
    }

    public function setMission(?Mission $Mission): self
    {
        $this->Mission = $Mission;

        return $this;
    }
}

src/Form/CibleType.php
<?php

namespace App\Form;

use App\Entity\Cible;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CibleType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom')
            ->add('prenom')
            ->add('date_naissance')
            ->add('nom_code')
            ->add('nationalite')
            ->add('Mission')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Cible::class,
        ]);
    }
}

src/Controller/CibleController.php
<?php

namespace App\Controller;

use App\Entity\Cible;
use App\Form\CibleType;
use App\Repository\CibleRepository;
use Doctrine\Persistence\ManagerRegistry;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

#[Route('/cible')]
class CibleController extends AbstractController
{
    
    #[Route('/', name: 'cible.list')]
    public function index(ManagerRegistry $doctrine, CibleRepository $repository, PaginatorInterface $paginator, Request $request): Response 
    
    {
        $cibles = $paginator->paginate(
        $cibles = $repository->findAll(),
            $request->query->getInt('page', 1), /*page number*/
            10 /*limit per page*/
        );

        $repository = $doctrine->getRepository(persistentObject: Cible::class);
        return $this->render('cible/index.html.twig', ['cibles' => $cibles,]);
    }


    
    #[Route('/{id<\d+>}', name: 'cible.detail')]
    public function detail(Cible $cible = null): Response 
    
    {

        if(!$cible) {
            $this->addFlash(type: 'error', message: "Le cible  n'existe pas");
            return $this->redirectToRoute('cible');
        }
        return $this->render('cible/detail.html.twig', ['cible' => $cible]);
    }

    #[Route('/detail', name: 'app_cible_detail', methods: ['GET'])]
    public function details(CibleRepository $cibleRepository, $id ): Response
    {


        return $this->render('cible/detail.html.twig', [
            'cibles' => $cibleRepository->findby($id),
        ]);
    }
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   // #[Route('/', name: 'app_cible_index', methods: ['GET'])]
   // public function index(CibleRepository $cibleRepository): Response
   // {
        //return $this->render('cible/index.html.twig', [
           // 'cibles' => $cibleRepository->findAll(),
        //]);
   // }

   // #[Route('/new', name: 'app_cible_new', methods: ['GET', 'POST'])]
    //public function new(Request $request, CibleRepository $cibleRepository): Response
   // {
      //  $cible = new Cible();
       // $form = $this->createForm(CibleType::class, $cible);
       // $form->handleRequest($request);

       // if ($form->isSubmitted() && $form->isValid()) {
           // $cibleRepository->add($cible, true);

           // return $this->redirectToRoute('app_cible_index', [], Response::HTTP_SEE_OTHER);
        //}

       // return $this->renderForm('cible/new.html.twig', [
        //    'cible' => $cible,
         //   'form' => $form,
        //]);
   // }

   // #[Route('/{id}', name: 'app_cible_show', methods: ['GET'])]
   // public function show(Cible $cible): Response
   // {
       // r//  'cible' => $cible,
       // ]);
  // }

   // #[Route('/{id}/edit', name: 'app_cible_edit', methods: ['GET', 'POST'])]
    //public function edit(Request $request, Cible $cible, CibleRepository $cibleRepository): Response
    //{
       // $form = $this->createForm(CibleType::class, $cible);
       // $form->handleRequest($request);

        //if ($form->isSubmitted() && $form->isValid()) {
          // $cibleRepository->add($cible, true);

           // return $this->redirectToRoute('app_cible_index', [], Response::HTTP_SEE_OTHER);
       // }

      //  return $this->renderForm('cible/edit.html.twig', [
        //    'cible' => $cible,
          //  'form' => $form,
       // ]);
  //  }

    //#[Route('/{id}', name: 'app_cible_delete', methods: ['POST'])]
   // public function delete(Request $request, Cible $cible, CibleRepository $cibleRepository): Response
   // {
     //   if ($this->isCsrfTokenValid('delete'.$cible->getId(), $request->request->get('_token'))) {
      //      $cibleRepository->remove($cible, true);
        //}

      //  return $this->redirectToRoute('app_cible_index', [], Response::HTTP_SEE_OTHER);
  //  }
}

templates/cible/_delete_form.html.twig
<form method="post" action="{{ path('app_cible_delete', {'id': cible.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ cible.id) }}">
    <button class="btn">Delete</button>
</form>

templates/cible/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/cible/detail.html.twig
{% extends 'base.html.twig' %}

{% block title %}

{{ cible.nom }}
{% endblock %}

{% block body %}
<div class="row mt-3">
    <div class="card" style="width: 18rem;">
        <img src="https://www.potentiel-humain.eu/wp-content/uploads/2022/03/contrat_mission_potentiel_humain.png" class="card-img-top" alt="...">
        <div class="card-body">
<div class="alert alert-sucess">
<h1>{{ cible.nom }}</h1>
<p>{{ cible.prenom }}</p>
</div>
</div>

{% endblock %}

templates/cible/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Cible{% endblock %}

{% block body %}
    <h1>Edit Cible</h1>

    {{ include('cible/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_cible_index') }}">back to list</a>

    {{ include('cible/_delete_form.html.twig') }}
{% endblock %}

templates/cible/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des Cible {% endblock %}

{% block body %}


<h1> Liste des Cibles</h1>

<div class="row">
    {% for cible in cibles %}
    <div class="card" style="width: 18rem;">
      <img src="https://www.cadresenmission.com/wp-content/uploads/2020/07/Faire-un-rapport-de-fin-de-mission.jpg" class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title">{{ cible.nom }}</h5>
          <h6 class="card-subtitle mb-2 text-muted">{{ cible.prenom }}</h6>
          <a href="{{ path('cible.detail', {id: cible.id})}}" class="btn btn-primary">Voir le détail</a>
        </div>
      </div>
      {% endfor %}
</div>

<div class="navigation d-flex justify-content-center mt-4">
  {{ knp_pagination_render(cibles) }}
</div>
{% endblock %}

templates/cible/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Cible{% endblock %}

{% block body %}
    <h1>Create new Cible</h1>

    {{ include('cible/_form.html.twig') }}

    <a href="{{ path('app_cible_index') }}">back to list</a>
{% endblock %}

templates/cible/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Cible{% endblock %}

{% block body %}
    <h1>Cible</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ cible.id }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ cible.nom }}</td>
            </tr>
            <tr>
                <th>Prenom</th>
                <td>{{ cible.prenom }}</td>
            </tr>
            <tr>
                <th>Date_naissance</th>
                <td>{{ cible.dateNaissance ? cible.dateNaissance|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Nom_code</th>
                <td>{{ cible.nomCode }}</td>
            </tr>
            <tr>
                <th>Nationalite</th>
                <td>{{ cible.nationalite }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_cible_index') }}">back to list</a>

    <a href="{{ path('app_cible_edit', {'id': cible.id}) }}">edit</a>

    {{ include('cible/_delete_form.html.twig') }}
{% endblock %}