src/Entity/Mission.php
<?php

namespace App\Entity;

use App\Repository\MissionRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: MissionRepository::class)]
class Mission
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $titre_mission = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description_mission = null;

    #[ORM\Column(length: 255)]
    private ?string $nom_code = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $pays = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $type_mission = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $statut_mission = null;

    #[ORM\Column(type: Types::DATE_IMMUTABLE)]
    private ?\DateTimeImmutable $date_debut = null;

    #[ORM\Column(type: Types::DATE_IMMUTABLE)]
    private ?\DateTimeImmutable $date_fin = null;

    #[ORM\OneToMany(mappedBy: 'Mission', targetEntity: Agent::class)]
    private Collection $agents;

    #[ORM\OneToMany(mappedBy: 'Mission', targetEntity: Cible::class)]
    private Collection $cibles;

    #[ORM\OneToMany(mappedBy: 'Mission', targetEntity: Contact::class)]
    private Collection $contacts;

    #[ORM\OneToMany(mappedBy: 'Mission', targetEntity: Planque::class)]
    private Collection $planques;

    public function __construct()
    {
        $this->agents = new ArrayCollection();
        $this->cibles = new ArrayCollection();
        $this->contacts = new ArrayCollection();
        $this->planques = new ArrayCollection();
        $this->date_debut = new \DateTimeImmutable();
        $this->date_fin = new \DateTimeImmutable();
    

    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitreMission(): ?string
    {
        return $this->titre_mission;
    }

    public function setTitreMission(string $titre_mission): self
    {
        $this->titre_mission = $titre_mission;

        return $this;
    }

    public function getDescriptionMission(): ?string
    {
        return $this->description_mission;
    }

    public function setDescriptionMission(string $description_mission): self
    {
        $this->description_mission = $description_mission;

        return $this;
    }

    public function getNomCode(): ?string
    {
        return $this->nom_code;
    }

    public function setNomCode(string $nom_code): self
    {
        $this->nom_code = $nom_code;

        return $this;
    }

    public function getPays(): ?string
    {
        return $this->pays;
    }

    public function setPays(string $pays): self
    {
        $this->pays = $pays;

        return $this;
    }

    public function getTypeMission(): ?string
    {
        return $this->type_mission;
    }

    public function setTypeMission(string $type_mission): self
    {
        $this->type_mission = $type_mission;

        return $this;
    }

    public function getStatutMission(): ?string
    {
        return $this->statut_mission;
    }

    public function setStatutMission(string $statut_mission): self
    {
        $this->statut_mission = $statut_mission;

        return $this;
    }

    public function getDateDebut(): ?\DateTimeImmutable
    {
        return $this->date_debut;
    }

    public function setDateDebut(\DateTimeImmutable $date_debut): self
    {
        $this->date_debut = $date_debut;

        return $this;
    }

    public function getDateFin(): ?\DateTimeImmutable
    {
        return $this->date_fin;
    }

    public function setDateFin(\DateTimeImmutable $date_fin): self
    {
        $this->date_fin = $date_fin;

        return $this;
    }

    /**
     * @return Collection<int, Agent>
     */
    public function getAgents(): Collection
    {
        return $this->agents;
    }

    public function addAgent(Agent $agent): self
    {
        if (!$this->agents->contains($agent)) {
            $this->agents->add($agent);
            $agent->setMission($this);
        }

        return $this;
    }

    public function removeAgent(Agent $agent): self
    {
        if ($this->agents->removeElement($agent)) {
            // set the owning side to null (unless already changed)
            if ($agent->getMission() === $this) {
                $agent->setMission(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Cible>
     */
    public function getCibles(): Collection
    {
        return $this->cibles;
    }

    public function addCible(Cible $cible): self
    {
        if (!$this->cibles->contains($cible)) {
            $this->cibles->add($cible);
            $cible->setMission($this);
        }

        return $this;
    }

    public function removeCible(Cible $cible): self
    {
        if ($this->cibles->removeElement($cible)) {
            // set the owning side to null (unless already changed)
            if ($cible->getMission() === $this) {
                $cible->setMission(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Contact>
     */
    public function getContacts(): Collection
    {
        return $this->contacts;
    }

    public function addContact(Contact $contact): self
    {
        if (!$this->contacts->contains($contact)) {
            $this->contacts->add($contact);
            $contact->setMission($this);
        }

        return $this;
    }

    public function removeContact(Contact $contact): self
    {
        if ($this->contacts->removeElement($contact)) {
            // set the owning side to null (unless already changed)
            if ($contact->getMission() === $this) {
                $contact->setMission(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Planque>
     */
    public function getPlanques(): Collection
    {
        return $this->planques;
    }

    public function addPlanque(Planque $planque): self
    {
        if (!$this->planques->contains($planque)) {
            $this->planques->add($planque);
            $planque->setMission($this);
        }

        return $this;
    }

    public function removePlanque(Planque $planque): self
    {
        if ($this->planques->removeElement($planque)) {
            // set the owning side to null (unless already changed)
            if ($planque->getMission() === $this) {
                $planque->setMission(null);
            }
        }

        return $this;
    }
}

src/Form/MissionType.php
<?php

namespace App\Form;

use App\Entity\Mission;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class MissionType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('titre_mission')
            ->add('description_mission')
            ->add('nom_code')
            ->add('pays')
            ->add('type_mission')
            ->add('statut_mission')
            ->add('date_debut')
            ->add('date_fin')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Mission::class,
        ]);
    }
}

src/Controller/MissionController.php
<?php

namespace App\Controller;

use App\Entity\Mission;
use App\Repository\MissionRepository;
use Doctrine\Persistence\ManagerRegistry;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;


#[Route('/mission')]
class MissionController extends AbstractController
{  
    
    #[Route('/', name: 'mission.list')]
    public function index(ManagerRegistry $doctrine, MissionRepository $repository, PaginatorInterface $paginator, Request $request): Response 
    
    {
        $missions = $paginator->paginate(
            $missions = $repository->findAll(),
            $request->query->getInt('page', 1), /*page number*/
            10 /*limit per page*/
        );

        $repository = $doctrine->getRepository(persistentObject: Mission::class);
        return $this->render('mission/index.html.twig', ['missions' => $missions,]);
    }


    
    #[Route('/{id<\d+>}', name: 'mission.detail')]
    public function detail(Mission $mission = null): Response 
    
    {

        if(!$mission) {
            $this->addFlash(type: 'error', message: "La mission  n'existe pas");
            return $this->redirectToRoute('mission');
        }
        return $this->render('mission/detail.html.twig', ['mission' => $mission]);
    }

    #[Route('/detail', name: 'app_mission_detail', methods: ['GET'])]
    public function details(MissionRepository $missionRepository, $id ): Response
    {


        return $this->render('mission/detail.html.twig', [
            'missions' => $missionRepository->findby($id),
        ]);
    }
   
}

templates/mission/_delete_form.html.twig
<form method="post" action="{{ path('app_mission_delete', {'id': mission.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ mission.id) }}">
    <button class="btn">Delete</button>
</form>

templates/mission/detail.html.twig
{% extends 'base.html.twig' %}

{% block title %}

 {{mission.titreMission}} 
 
 {{mission.descriptionMission}}
{% endblock %}

{% block body %}


<div class="row mt-3">
    <div class="card" style="width: 18rem;">
        <img src="https://www.potentiel-humain.eu/wp-content/uploads/2022/03/contrat_mission_potentiel_humain.png" class="card-img-top" alt="...">
        <div class="card-body">
<div class="alert alert-sucess">
<h1>{{mission.titreMission}}</h1>
</div>
</div>

{% endblock %}

templates/mission/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Mission{% endblock %}

{% block body %}
    <h1>Edit Mission</h1>

    {{ include('mission/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_mission_index') }}">back to list</a>

    {{ include('mission/_delete_form.html.twig') }}
{% endblock %}

templates/mission/index.html.twig
{% extends 'base.html.twig' %}

{% block title %} Liste des Missions{% endblock %}

{% block body %}


<h1> Liste des Missions</h1>

<div class="row">
    {% for mission in missions %}
    <div class="card" style="width: 18rem;">
      <img src="https://www.cadresenmission.com/wp-content/uploads/2020/07/Faire-un-rapport-de-fin-de-mission.jpg" class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title">{{mission.titreMission}}</h5>
          <h6 class="card-subtitle mb-2 text-muted">{{mission.descriptionMission}}</h6>
          <a href="{{ path('mission.detail', {id: mission.id})}}" class="btn btn-primary">Voir le détail</a>
        </div>
      </div>
      {% endfor %}
</div>

<div class="navigation d-flex justify-content-center mt-4">
  {{ knp_pagination_render(missions) }}
</div>

{% endblock %}

templates/mission/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Mission{% endblock %}

{% block body %}
    <h1>Create new Mission</h1>

    {{ include('mission/_form.html.twig') }}

    <a href="{{ path('app_mission_index') }}">back to list</a>
{% endblock %}

templates/mission/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mission{% endblock %}

{% block body %}
    <h1>Mission</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ mission.id }}</td>
            </tr>
            <tr>
                <th>Titre_mission</th>
                <td>{{ mission.titreMission }}</td>
            </tr>
            <tr>
                <th>Description_mission</th>
                <td>{{ mission.descriptionMission }}</td>
            </tr>
            <tr>
                <th>Nom_code</th>
                <td>{{ mission.nomCode }}</td>
            </tr>
            <tr>
                <th>Pays</th>
                <td>{{ mission.pays }}</td>
            </tr>
            <tr>
                <th>Type_mission</th>
                <td>{{ mission.typeMission }}</td>
            </tr>
            <tr>
                <th>Statut_mission</th>
                <td>{{ mission.statutMission }}</td>
            </tr>
            <tr>
                <th>Date_debut</th>
                <td>{{ mission.dateDebut ? mission.dateDebut|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Date_fin</th>
                <td>{{ mission.dateFin ? mission.dateFin|date('Y-m-d') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_mission_index') }}">back to list</a>

    <a href="{{ path('app_mission_edit', {'id': mission.id}) }}">edit</a>

    {{ include('mission/_delete_form.html.twig') }}
{% endblock %}