src/Entity/Planque.php
<?php

namespace App\Entity;

use App\Repository\PlanqueRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PlanqueRepository::class)]
class Planque
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $code_planque = null;

    #[ORM\Column(length: 255)]
    private ?string $adresse = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $pays = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $type_planque = null;

    #[ORM\ManyToOne(inversedBy: 'planques')]
    private ?Mission $Mission = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCodePlanque(): ?string
    {
        return $this->code_planque;
    }

    public function setCodePlanque(string $code_planque): self
    {
        $this->code_planque = $code_planque;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getPays(): ?string
    {
        return $this->pays;
    }

    public function setPays(string $pays): self
    {
        $this->pays = $pays;

        return $this;
    }

    public function getTypePlanque(): ?string
    {
        return $this->type_planque;
    }

    public function setTypePlanque(string $type_planque): self
    {
        $this->type_planque = $type_planque;

        return $this;
    }

    public function getMission(): ?Mission
    {
        return $this->Mission;
    }

    public function setMission(?Mission $Mission): self
    {
        $this->Mission = $Mission;

        return $this;
    }
}

src/Form/PlanqueType.php
<?php

namespace App\Form;

use App\Entity\Planque;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PlanqueType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('code_planque')
            ->add('adresse')
            ->add('pays')
            ->add('type_planque')
            ->add('Mission')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Planque::class,
        ]);
    }
}

src/Controller/PlanqueController.php
<?php

namespace App\Controller;

use App\Entity\Planque;
use App\Form\PlanqueType;
use App\Repository\PlanqueRepository;
use Knp\Component\Pager\PaginatorInterface;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

#[Route('/planque')]
class PlanqueController extends AbstractController
{

    #[Route('/', name: 'planque.list')]
    public function index(ManagerRegistry $doctrine, PlanqueRepository $repository, PaginatorInterface $paginator, Request $request): Response 
    
    {
        $planques = $paginator->paginate(
        $planques = $repository->findAll(),
            $request->query->getInt('page', 1), /*page number*/
            10 /*limit per page*/
        );

        $repository = $doctrine->getRepository(persistentObject: Planque::class);
        return $this->render('planque/index.html.twig', ['planques' => $planques,]);
    }


    
    #[Route('/{id<\d+>}', name: 'planque.detail')]
    public function detail(Planque $planque = null): Response 
    
    {

        if(!$planque) {
            $this->addFlash(type: 'error', message: "La planque  n'existe pas");
            return $this->redirectToRoute('planque');
        }
        return $this->render('planque/detail.html.twig', ['planque' => $planque]);
    }

    #[Route('/detail', name: 'app_planque_detail', methods: ['GET'])]
    public function details(PlanqueRepository $planqueRepository, $id ): Response
    {


        return $this->render('planque/detail.html.twig', [
            'planques' => $planqueRepository->findby($id),
        ]);
    }



    //#[Route('/', name: 'app_planque_index', methods: ['GET'])]
   // public function index(PlanqueRepository $planqueRepository): Response
   // {
       // return $this->render('planque/index.html.twig', [
            //'planques' => $planqueRepository->findAll(),
       // ]);
   // }

   // #[Route('/new', name: 'app_planque_new', methods: ['GET', 'POST'])]
    //public function new(Request $request, PlanqueRepository $planqueRepository): Response
    //{
       // $planque = new Planque();
        //$form = $this->createForm(PlanqueType::class, $planque);
        //$form->handleRequest($request);

       // if ($form->isSubmitted() && $form->isValid()) {
           // $planqueRepository->add($planque, true);

           // return $this->redirectToRoute('app_planque_index', [], Response::HTTP_SEE_OTHER);
       // }

       //return $this->renderForm('planque/new.html.twig', [
            //'planque' => $planque,
           // 'form' => $form,
       // ]);
    //}

    //#[Route('/{id}', name: 'app_planque_show', methods: ['GET'])]
   // public function show(Planque $planque): Response
    //{
      //  return $this->render('planque/show.html.twig', [
           // 'planque' => $planque,
       // ]);
   // }

   // #[Route('/{id}/edit', name: 'app_planque_edit', methods: ['GET', 'POST'])]
   // public function edit(Request $request, Planque $planque, PlanqueRepository $planqueRepository): Response
    //{
       // $form = $this->createForm(PlanqueType::class, $planque);
       // $form->handleRequest($request);

       // if ($form->isSubmitted() && $form->isValid()) {
          //  $planqueRepository->add($planque, true);

          //  return $this->redirectToRoute('app_planque_index', [], Response::HTTP_SEE_OTHER);
       // }

       // return $this->renderForm('planque/edit.html.twig', [
          //  'planque' => $planque,
           // 'form' => $form,
       // ]);
   // }

   // #[Route('/{id}', name: 'app_planque_delete', methods: ['POST'])]
    //public function delete(Request $request, Planque $planque, PlanqueRepository $planqueRepository): Response
   // {
      //  if ($this->isCsrfTokenValid('delete'.$planque->getId(), $request->request->get('_token'))) {
         //   $planqueRepository->remove($planque, true);
       // }

       // return $this->redirectToRoute('app_planque_index', [], Response::HTTP_SEE_OTHER);
   // }
}

templates/planque/_delete_form.html.twig
<form method="post" action="{{ path('app_planque_delete', {'id': planque.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ planque.id) }}">
    <button class="btn">Delete</button>
</form>

templates/planque/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/planque/detail.html.twig
{% extends 'base.html.twig' %}

{% block title %}

{{ planque.codePlanque }}
{% endblock %}

{% block body %}
<div class="row mt-3">
    <div class="card" style="width: 18rem;">
        <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSEBEsk1eeoq-di8tPBad9Ez8KFRvqz43eH0A&usqp=CAU" class="card-img-top" alt="...">
        <div class="card-body">
<div class="alert alert-sucess">
<h1>{{ planque.codePlanque }}</h1>
<p>{{ planque.adresse }}</p>
</div>
</div>

{% endblock %}

templates/planque/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Planque{% endblock %}

{% block body %}
    <h1>Edit Planque</h1>

    {{ include('planque/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_planque_index') }}">back to list</a>

    {{ include('planque/_delete_form.html.twig') }}
{% endblock %}

templates/planque/index.html.twig
{% extends 'base.html.twig' %}

{% block title %} Liste de Planque {% endblock %}


{% block body %}


<h1> Liste des Planques</h1>

<div class="row">
    {% for planque in planques %}
    <div class="card" style="width: 18rem;">
      <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTF6SBoZ2k-B1Ykci00Xp6B1S6WerjsQPKDcQ&usqp=CAU" class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title">{{ planque.codePlanque }}</h5>
          <h6 class="card-subtitle mb-2 text-muted">{{ planque.adresse }}</h6>
          <a href="{{ path('planque.detail', {id: planque.id})}}" class="btn btn-primary">Voir le détail</a>
        </div>
      </div>
      {% endfor %}
</div>

<div class="navigation d-flex justify-content-center mt-4">
  {{ knp_pagination_render(planques) }}
</div>


{% endblock %}

templates/planque/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Planque{% endblock %}

{% block body %}
    <h1>Create new Planque</h1>

    {{ include('planque/_form.html.twig') }}

    <a href="{{ path('app_planque_index') }}">back to list</a>
{% endblock %}

templates/planque/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Planque{% endblock %}

{% block body %}
    <h1>Planque</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ planque.id }}</td>
            </tr>
            <tr>
                <th>Code_planque</th>
                <td>{{ planque.codePlanque }}</td>
            </tr>
            <tr>
                <th>Adresse</th>
                <td>{{ planque.adresse }}</td>
            </tr>
            <tr>
                <th>Pays</th>
                <td>{{ planque.pays }}</td>
            </tr>
            <tr>
                <th>Type_planque</th>
                <td>{{ planque.typePlanque }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_planque_index') }}">back to list</a>

    <a href="{{ path('app_planque_edit', {'id': planque.id}) }}">edit</a>

    {{ include('planque/_delete_form.html.twig') }}
{% endblock %}